platform :ios, '12.0'

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

target 'greet-native-demo' do
  use_frameworks!

  pod 'GreetSolutions', :git => 'https://github.com/Xyberfocus/GreetSolutionsSDKiOS.git'

  use_expo_modules!
end